- name: setup bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
      - name: Import VPC variables
        include_vars: vars/vpc_setup

      - name: Import vpc setup vaiable
        include_vars: vars/output_vars

      - name: create a ec2 key
        ec2_key:
          name: vprofile-key
          region: "{{region}}"
        register: key_out

      - name: save private key information in bastion file
        copy:
          content: "{{key_out.key.private_key}}"
          dest: "./bastion-key.pem"
          mode: 0600
        when: key_out.changed

      - name: create security group for bastion host
        ec2_group:
          name: Bastion-host-sg
          description: allow port 22 from everywhere
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          rules:
             - proto: tcp
               from_port: 22
               to_port: 22
               cidr_ip: "{{MYIP}}"
        register: BastionSG_out

      - name: creating Bastion host
        ec2:
          key_name: vprofile-key
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{bastion_ami}}"
          wait: yes
          wait_timeout: 300
          instance_tags:
               Name: "Bastion_host"
               Project: Vprofile
               Owner: Devops Team
          exact_count: 1
          count_tag:
              Name: "Bastion_host"
              Project: Vprofile
              Owner: Devops Team
          group_id: "{{BastionSG_out.group_id}}"
          vpc_subnet_id: "{{pubsub1id}}"
        register: BastionHost_out







