- name: setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
       - name: Import VPC setup variables
         include_vars: vars/output_vars

       - name: Import vprofile setup variables
         include_vars: vars/vprostacksetup

       - name: create a ec2 key
         ec2_key:
               name: vpro-key
               region: "{{region}}"
         register: vprokey_out

       - name: save private key information into the file loginkey_vpro.pem
         copy:
               content: "{{vprokey_out.private_key}}"
               dest: "./loginkey_vpro.pem"
               mode: 0600
         when: vprokey_out.changed

